PM / QoS: export pm_qos_update_request_timeout
When compiling input-cfboost as a module, there is an error:

    ERROR: "pm_qos_update_request_timeout"
    [drivers/input/input-cfboost.ko] undefined!

So this patch fixes it by exporting the function.

Bug 1887171
Bug 200305104

Change-Id: Id0a52492b3ab28e3cd618579714c4edfc4b5e869
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: http://git-master/r/1323582
(cherry picked from commit 4a857a18406a978c2e1588b4630ca4f5a58a6ee3)
Reviewed-on: http://git-master/r/1490918
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>