platform: tegra: fix .._get_powergate_id const correctness
Fix compilation warnings/errors caused by missing const declaration:
drivers/usb/host/xhci-tegra.c:1089:21: error: passing argument 1 of 'tegra_pd_get_powergate_id' discards 'const' qualifier from pointer target type [-Werror]
  tegra->pgid_host = tegra_pd_get_powergate_id(tegra_xusbc_pd);

Change-Id: I79a13bd6b6594ae850dc5f6e8ccaa1e370f0b35a
Signed-off-by: Timo Alho <talho@nvidia.com>
Reviewed-on: http://git-master/r/1279520
Reviewed-by: Mikko Perttunen <mperttunen@nvidia.com>