spi: tegra: Remove inline CONFIG_DEBUG_FS check
The tegra_spi_debugfs_init() is already defined with CONFIG_DEBUG_FS
protection. Having this extra inline check causes build error during
the test of CONFIG_DEBUG_FS=n:
    drivers/spi/spi-tegra114.c:1869:13: error:
      ‘tegra_spi_debugfs_init’ defined but not ed

So this patch just simply removes it to fix the build error.

Bug 2284925

Change-Id: I2d71c3cf97654126a3368324dd68c245ffe51fa3
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1803454
GVS: Gerrit_Virtual_Submit
Reviewed-by: Krishna Yarlagadda <kyarlagadda@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>