iommu: arm-smmu: fix unused variable warning
Fix unused variable warning when __PAGETABLE_PMD_FOLDED is 
defined.

drivers/iommu/arm-smmu.c:
In function 'arm_smmu_alloc_init_pmd':
drivers/iommu/arm-smmu.c:2011:26:
error: unused variable 'smmu' [-Werror=unused-variable]
  struct arm_smmu_device *smmu = domain->smmu;

Bug 1990842

Change-Id: I51433003acbf1a9647b943d59dbb7e92d31bf6e6
Signed-off-by: Krishna Reddy <vdumpa@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1599824
GVS: Gerrit_Virtual_Submit
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>