Revert "drivers: spi: Avoid division by zero"
This reverts commit 6ac35c4d87fc23a413c8b3716a56d7857c535e34
since this causes a build break.

kernel-4.9/drivers/spi/spi-tegra124-slave.c: In function 'tegra_spi_transfer_one_message':
kernel-4.9/drivers/spi/spi-tegra124-slave.c:1206:5: error: 'cdiv' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  if (cdiv < tspi->min_div) {
     ^
kernel-4.9/drivers/spi/spi-tegra124-slave.c:1172:15: note: 'cdiv' was declared here
  unsigned int cdiv, fin_err = rate;
               ^
cc1: all warnings being treated as errors
make[4]: *** [drivers/spi/spi-tegra124-slave.o] Error 1
make[3]: *** [drivers/spi] Error 2
make[2]: *** [drivers] Error 2

Change-Id: Ia4173bd169e763344ca4d199723eff9e43f39a5e
Reviewed-on: https://git-master/r/1509484
Reviewed-by: Laxman Dewangan <ldewangan@nvidia.com>
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Tested-by: Bharat Nihalani <bnihalani@nvidia.com>