memory: tegra: fix unused-variable warning for emc_override_rate
emc_override_rate is getting used in suspend/resume so using it
only when CONFIG_PM_SLEEP is defined.

It will fixing following warning:

kernel-4.4/drivers/memory/tegra/tegra210-emc.c:136:22
error: 'emc_override_rate' defined but not used [-Werror=unused-variable]
static unsigned long emc_override_rate;
                     ^

Bug 200294364

Change-Id: Iab797a5a6fc5fd2e00d15d6b8c6058e32b4b0ea7
Signed-off-by: Pritesh Raithatha <praithatha@nvidia.com>
Reviewed-on: http://git-master/r/1453115
(cherry picked from commit 186175adf3c165fda978f52929827aa0e3facc6f)