sched: drop ignored const in return type of sched_domain_energy_f
The unnecessary const in the typedef of sched_domain_energy_f produces
the following compiler message with -Werror, so remove it because it
does not guard any actual value from being changed:

include/linux/sched.h:1217:42: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]

Bug 1853519

Change-Id: Iad0e825aed8be5c0ec7b71b6d78b3b0e5805bfbd
Signed-off-by: Konsta Holtta <kholtta@nvidia.com>
Reviewed-on: http://git-master/r/1327689
Reviewed-by: Mikko Perttunen <mperttunen@nvidia.com>
Reviewed-by: Timo Alho <talho@nvidia.com>
GVS: Gerrit_Virtual_Submit