mm: add explicit cast in comparison of zone type and int
The lack of explicit typecast produces the following compiler message
with -Werror when comparing an integer and an enum, so cast the enum to
int because the function zonelist_zone_idx returns an int already:

include/linux/mmzone.h: In function 'next_zones_zonelist':
include/linux/mmzone.h:965:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

Bug 1853519

Change-Id: I3243c569cf4cd25e66ec2d5322127d30d02f301e
Signed-off-by: Konsta Holtta <kholtta@nvidia.com>
Reviewed-on: http://git-master/r/1327688
Reviewed-by: Mikko Perttunen <mperttunen@nvidia.com>
Reviewed-by: Timo Alho <talho@nvidia.com>
GVS: Gerrit_Virtual_Submit