clk: tegra: Link dt_ids of cap_vcore_ape and cap_vcore_cbus
The tegra-core-action driver failed to get its essitial clock via DT:
 tegra_core_action core_dvfs_cdev_floor:
                    Tegra CORE DVFS 'floor cooling device' registered
 ERROR: could not get clock /core_dvfs_cdev_cap:cbus_cap(2)
 tegra_core_action core_dvfs_cdev_cap: Failed to get cap clk cbus_cap
 tegra_core_action: probe of core_dvfs_cdev_cap failed with error -2

This is because the cbus clock in the clock tree has not been linked
to its Device Tree id. So this patch tries to fix it by linking them.

It also adds one to cap_vcore_ape since the tegra-core-action driver
needs that one too.

Bug 200340064

Change-Id: I866c2262f135c7234729c19b1c12d749cb954ddb
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1595546
Reviewed-by: Aleksandr Frid <afrid@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>