pcie: host: tegra: fix unused function build issue
Fix following compilation issue pointed by clang

pci-tegra.c:536:20: error: unused function 'pads_writel'
pci-tegra.c:542:19: error: unused function 'pads_readl'

bug 1745660

Change-Id: Iba01a9a2c37a3afd80eee070555bd905878d9b43
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1152616
(cherry picked from commit 9e6585ed40e966f9ee9af2556e4f5050d9667ef3)
Reviewed-on: http://git-master/r/1159922
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>